package cn.wizzer.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-02T22:40:27.449+08:00
 * Generated source version: 3.1.7
 * 
 */
public interface HelloWordImplPortType {

    @WebMethod
    public String sayHello(@WebParam(name="userName") String userName);

    public void setUser(String userName);
}
